### ISSUE TITLE
[QUESTION/BUGGSS]: Class "RichText" not found

### ISSUE THREAD

**Issue by NaMeTaKeN33** [shahmal1yev/blueskysdk#18]
### Describe the bug

In the process of switching from Twitter to BSky for my app and site. Didn't see anything in the docs that referenced the class

```php
require_once('AUTOLOAD-LOCATION');

use Atproto\Client;
use Atproto\Lexicons\{
    App\Bsky\Feed\Post
};

$bluesky = new Client();
$bluesky->authenticate('USER', 'PASS');

$bluesky->app()
    ->bsky()
    ->feed()
    ->post()
    ->forge()
    ->text(
        "*TEST* StringOne",
        RichText::tag('hashtag', 'hashtag'),
        " StringTwo ",
        RichText::link('https://google.com', 'Google - URL Preview Test')
    )
    ->send();
```

**ERROR**
PHP Fatal error:  Uncaught Error: Class "RichText" not found

### Steps to reproduce

1. Install using composer using 'dev-main' branch (stable is not available yet)
2. Create a blank PHP document and use the code above

### Expected behavior

The code from the doc should post to Blue Sky

### PHP Version

PHP 8.1

### Package Version

dev-main

### Relevant log output

```shell
PHP Fatal error:  Uncaught Error: Class "RichText" not found
```

**Comment by shahmal1yev** [comment]
Hi! Thanks for reporting this issue. Looking at your code, I notice you're trying to use `RichText` directly, but that's not the correct way to use the SDK.

- To create a post, you need 3 lexicons: `createSession`, `post`, and `createRecord`
- createSession is already handled by the `authenticate` method
- You can find the paths for others here: https://docs.bsky.app/docs/category/http-reference
- `Client` helps you create these easily, so you don't need to autoload them with `use`
- However, `RichText` Factory is different. If you want to use it, you need to autoload it


```php
<?php

require_once('vendor/autoload.php');

use Atproto\Client;

// You seem to have forgotten to include this
use Atproto\Lexicons\App\Bsky\RichText\RichText;


$bsky = (new Client())->authenticate('handle', 'pass');

/** @var Atproto\Lexicons\App\Bsky\Feed\Post $post */
$post = $bsky->app()->bsky()->feed()->post()->forge()
    ->text(
        "*TEST* StringOne ",
        RichText::tag('hashtag', 'hashtag'),
        " StringTwo ",
        RichText::link('https://google.com', 'Google - URL Preview Test')
    );

/** @var Atproto\Lexicons\Com\Atproto\Repo\CreateRecord $createRecord */
$createRecord = $bsky->com()->atproto()->repo()->createRecord()->forge()
    ->record($post) // Pass the post to be sent
    // specify other required data
    ->repo($bsky->authenticated()->did())
    ->collection($post->nsid());

// send and get response instance
/** @var Atproto\Responses\Com\Atproto\Repo\CreateRecordResponse $response */
$response = $createRecord->send();

/** @var string $postUri */
$postUri = $response->uri();

echo $postUri;
```

**Comment by shahmal1yev** [comment]
Additionally, I want to show an easier way to use it:

```php
<?php

require_once('vendor/autoload.php');

use Atproto\Client; // You don't need to autoload anything else

$bsky = new Client();

$bsky->authenticate('handle', 'pass');

$post = $bsky->app()->bsky()->feed()->post()->forge()
    ->text("*TEST* StringOne ")
    ->tag('hashtag')
    ->text(' StringTwo ')
    ->link('https://google.com', 'Google - URL Preview Test');

$createRecord = $bsky->com()->atproto()->repo()->createRecord()->forge()
    ->record($post)
    ->repo($bsky->authenticated()->did())
    ->collection($post->nsid());

$response = $createRecord->send();

$postUri = $response->uri();

echo $postUri;

```

If you need any additional help, don't hesitate to ask.

**Comment by NaMeTaKeN33** [comment]
Yup. That was it. Was just missing RichText include. Are there any docs on external URL embeds? 

`->link('https://google.com', 'Google')`

just returns a string link. Looking at adding embed that will show opengraph meta information and image when a URL is added. I've added:

`use Atproto\Lexicons\App\Bsky\Embed\External;`
`->embed(new External('https://google.com', 'Google Title', 'Google Desc'));`

but no luck so far

**Comment by shahmal1yev** [comment]
After you mentioned this, I realized it. I did some research, looked at the documentation, and couldn't find any related `issue`. I also checked implementations in other SDKs to clarify, and it seems the situation is the same there.

I understand that for some reason, the Bluesky API doesn't provide preview support for links during post creation. However, there is a solution.

Using link and external embed together.

```php
<?php

use Atproto\Client;
use Atproto\Lexicons\App\Bsky\Embed\External;

$client = new Client();
$client->authenticate('handle', 'password');

$external = $client->app()->bsky()->embed()->external()->forge(
    'https://shahmal1yev.dev',
    'Come to my blog',
    'A personal blog about development and cybersecurity'
);

$post = $client->app()->bsky()->feed()->post()->forge()
    ->text('This is a test post: shahmal1yev.dev')
    ->embed($external);

$createRecord = $client->com()->atproto()->repo()->createRecord()->forge()
    ->record($post)
    ->repo($client->authenticated()->did())
    ->collection($post->nsid());

$response = $createRecord->send();

echo $response->uri();
```

> [!IMPORTANT]  
> **I discovered a small bug in `External`. Please update the package after the latest PR referencing this issue**
```bash
composer update shahmal1yev/blueskysdk
```

**Comment by shahmal1yev** [comment]
The issue was fixed. You can use it now

**Comment by shahmal1yev** [comment]
I've confirmed my answer; link previews are actually generated on the client side...

This means that if you're creating posts directly via the API and want to include link previews, you'll need to handle preview generation and embedding separately on the client side.

https://atproto-browser.vercel.app/at/did:plc:cbkjy5n7bk3ax2wplmtjofq2/app.bsky.feed.post/3lap25jkeg22n

**Comment by MeesterPaul** [comment]
@shahmal1yev can you provide an example of the code needed to generate a link preview with thumbnail? I've run into two problems so far: 
1. the mimeType check in the thumb function of seems to be incorrect, it's rejecting correct image types because of what I think is an incorrect use of a wildcard in the search pattern for str_starts_with – line 77 of Embed/External.php https://github.com/shahmal1yev/blueskysdk/blob/2c5bd3a7653d63a2b5ccf9e43e2de300891de0dc/src/Lexicons/App/Bsky/Embed/External.php#L77
2. Amending the mimeType check allows a blob to be attached to the record as expected but it's still not appearing as a link preview image. 

Also, what is the correct procedure for outputting the generated request as sent to Bluesky? This would be useful for debugging the problem.

**Comment by shahmal1yev** [comment]
Hi, there! Here we are, again...

Thank you so much, @MeesterPaul, for reporting these issues!

You can pass any object that implements the [`LexiconContract`](https://github.com/shahmal1yev/blueskysdk/blob/main/src/Contracts/LexiconContract.php) as the first argument to `json_decode()` or `json_encode()` for serialization.

Additionally, in the [new version (v1.4.2-beta)](https://github.com/shahmal1yev/blueskysdk/releases/tag/v1.4.2-beta), you can now use the [`External`](https://github.com/shahmal1yev/blueskysdk/blob/main/src/Lexicons/App/Bsky/Embed/External.php) class for creating posts with preview cards.

Here's an example of how to use it, along with the [result](https://bsky.app/profile/shahmal1yevv.bsky.social/post/3lbzexpnr3k2a):

```php
<?php

use Atproto\Client;

$client = new Client();
$client->authenticate('handle', 'password');

$uploadedBlob = $client->com()->atproto()->repo()->uploadBlob()->forge()
    ->token($client->authenticated()->accessJwt())
    ->blob('path_of_image')
    ->send()
    ->blob();

$external = $client->app()->bsky()->embed()->external()->forge(
    'https://shahmal1yev.dev',
    'Eldar Shahmaliyev\'s blog',
    'A personal blog about cybersecurity and development.'
)->thumb($uploadedBlob);

$post = $client->app()->bsky()->feed()->post()->forge()
    ->text('This is a test post: ')
    ->link('https://shahmal1yev.dev', 'shahmal1yev.dev')
    ->embed($external);

$createRecord = $client->com()->atproto()->repo()->createRecord()->forge()
    ->record($post)
    ->repo($client->authenticated()->did())
    ->collection($post->nsid());

$response = $createRecord->send();

echo $response->uri();
```

Let me know if you have any further questions or need assistance. Thanks again for your valuable feedback!

**Comment by MeesterPaul** [comment]
All working as expected now, thank you!
