### ISSUE TITLE
[Feature]: Search Posts

### ISSUE THREAD

**Issue by dev4press** [shahmal1yev/blueskysdk#29]
### Is your feature request related to a problem?

Implement SearchPosts endpoint as described here:
https://docs.bsky.app/docs/api/app-bsky-feed-search-posts

### Describe the solution you'd like

Implement search with all the supported request parameters.

### Priority

High

**Comment by shahmal1yev** [comment]
Thank you, @dev4press, for suggesting this functionality!

The SearchPosts feature is currently under development: #30

This feature will fully support all query parameters as outlined in the Bluesky API endpoint (app.bsky.feed.searchPosts).

If you have any suggestions or additional feedback, I would be happy to consider them.

The PR will soon be merged, and the release will be published. Thank you again for your suggestion, and I look forward to more in the future!

**Comment by dev4press** [comment]
Thanks, I see the 1.5 Beta includes the Search, but I can't figure out how to send the search request. 

```php
$client = new Client();
$client->authenticate( $id, $password );
$response = $client->app()->bsky()->feed()->searchPosts($client, 'test')->send();
```

How should this work? And, how to add extra search elements (tag, URL...)?

Also, can you update examples in the readme, most things are not working for me with the latest SDK version.

Milan

**Comment by shahmal1yev** [comment]
Hello Milan,

Apologies for the delay in getting back to you. The reason for the delay was that I was refining the `SearchPosts` implementation to ensure it provides the best functionality and flexibility. Additionally, I had to make some minor adjustments to the SDK to align it with my internal standards. These issues should be completely resolved with the 2.x release.

Now that it’s finalized, here’s how you can use it effectively:

### Sending a Search Request
Here’s an example of how to create and send a search request using the latest implementation:

```php
$client = new Client();
$client->authenticate($id, $password);

$response = $client->app()->bsky()->feed()->searchPosts()->forge('query') // Enter your query here
    ->tag(['tag1', 'tag2']) // Optional: Add tags
    ->url('https://example.com') // Optional: Add a URL
    ->lang('en') // Optional: Add a language filter
    ->limit(5) // Optional: Limit the number of results
    ->send();
```

This will return posts based on your query and the filters you’ve applied.

### Accessing the Response
To retrieve posts from the `response`, you can use the following:

```php
$posts = $response->posts();

foreach ($posts as $post) {
    echo $post->record()->text() . PHP_EOL;

    // Additional processing...
}
```

### Key Notes

Please, see this short discussion on Discord:  
[https://discord.com/channels/1097580399187738645/1097580399187738648/1316099957106671757](https://discord.com/channels/1097580399187738645/1097580399187738648/1316099957106671757)  

I’ll also attach a relevant screenshot for reference

![Screenshot From 2024-12-11 02-08-25](https://github.com/user-attachments/assets/6dfa5615-53b7-46cb-8070-69ef0ee22976)

### README Update

I’ve noted your concern about the README. Updating the documentation to reflect the latest features and examples is a priority, and I’ll ensure it’s easier to integrate. You’ll primarily find updates and guides here:  
[SDK Docs](https://blueskysdk.shahmal1yev.dev)

Let me know if this resolves your queries. Feel free to share any additional feedback or issues you encounter.

**Comment by dev4press** [comment]
Thanks! I will check this out over the weekend and let you know if I have any issues.

**Comment by dev4press** [comment]
I have just one question. The [Bluesky documentation](https://docs.bsky.app/docs/api/app-bsky-feed-search-posts) shows that response should include `hitsTotal` value. But, any call I make, returns list of posts (limited by limit option) and the cursor value. Is this the issue with the Bluesky API response, or your SDK?

**Comment by edevsh** [comment]
`hitsTotal` is an optional item in the response, as indicated by the HTTP reference of bsky. This means it may not always be present in the response.

Additionally, you can retrieve any values from the response object using methods named according to the HTTP reference of Bsky. For example:

```php
$hitsTotal = $response->hitsTotal();
```

To avoid exceptions when a key might not exist, use the `has()` method to check its presence before accessing it:

```php
if ($response->has('hitsTotal')) {
    $hitsTotal = $response->hitsTotal(); // Alternatively, $response->resolve('hitsTotal');
}
```

This approach ensures safe access to optional response fields.

**Comment by dev4press** [comment]
Thanks, I tried it. Right now, no response includes hitsTotal value, even if I search for something I am sure has a lot of results (for instance, search for 'bluesky' - it returns as many posts as the request limit specifies and cursor value set to the limit value), but there is no total number of results. If search doesn't return total number of results, it is useless for tracking how many times some URL has been posted, for instance.

I am not sure how responsive Bluesky support is, I would open a support ticket to see why the total hits is not returned.

Milan

**Comment by edevsh** [comment]
Please take a look at these:  

- https://github.com/bluesky-social/atproto/issues/3020  
- https://github.com/bluesky-social/atproto/issues/1856
