### ISSUE TITLE
[Bug]: Getting Error :  Call to undefined method Atproto\Lexicons\App\Bsky\Feed\Post::send()

### ISSUE THREAD

**Issue by nalindev** [shahmal1yev/blueskysdk#41]
### Describe the bug

I am trying to run this script locally but i am still getting this error and the reason seems to be unclear for me. can you please help me? thanks in advance..

my code - 
![image](https://github.com/user-attachments/assets/a3da050f-2e85-40b1-9b6f-059285a7bf4d)

error screenshot
![image](https://github.com/user-attachments/assets/f3f851ff-bd9b-4944-b7b3-64093daf31a0)

### Steps to reproduce

using wamp server 
php version - 8.3
![image](https://github.com/user-attachments/assets/c64b523a-6fdf-4dae-9d41-37efade71357)

### Expected behavior

The expected behavior is to post the message "Hello!" on Bluesky.

### PHP Version

PHP 8.2

### Package Version

v1.5.0-beta1

**Comment by shahmal1yev** [comment]
Hi, @nalindev! Thanks for reporting this, but this is an invalid issue. And yes, you are correct, this stems from the readme.md file, and I should have updated it.

Please take a look here: [Creating Posts on Bluesky with BlueSky SDK](https://blueskysdk.shahmal1yev.dev/blog/creating-posts-on-bluesky-with-blueskysdk/)

And here: https://github.com/shahmal1yev/blueskysdk/issues/18#issuecomment-2469004244
